name: Превью сайта на Surge

on:
  pull_request

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка контента
        uses: actions/checkout@v2
      - name: Сборка и публикация превью сайта на Surge
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: _site
          build: |
            npm ci
            npm run build
      - name: Отображение сообщения в интерфейсе GitHub Actions
        run: echo "Ссылка на превью ${{ steps.preview_step.outputs.preview_url }}"
